	  
	apiVersion: v1
	kind: Pod
	metadata:
	  name: nginx
	spec:
	  containers:
		- name: nginx
		  image: nginx 
		  volumeMounts:
		  - name: nginx-config
			mountPath: /usr/share/nginx/html/
	  volumes:
		- name: nginx-config
		  configMap:
			name: nginx-config
---

	 apiVersion: v1
	data:
	  index.html: "<h1>\n\thello world this is cdec online batch we are learing kubernetes
		\n</h1>\n"
	kind: ConfigMap
	metadata:
	  creationTimestamp: null
	  name: nginx-config
